// Source code is decompiled from a .class file using FernFlower decompiler (from Intellij IDEA).
package com.martin.appserver.database;

public class DBSchema {
   public DBSchema() {
   }

   public static String[] getCreateTableStatements() {
      return new String[]{"CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, whatsapp TEXT, password TEXT, role TEXT NOT NULL, status TEXT NOT NULL, avatar TEXT, created_at INTEGER NOT NULL)", "CREATE TABLE IF NOT EXISTS company_config (id INTEGER PRIMARY KEY CHECK (id = 1), company_name TEXT, username TEXT, pin TEXT, primary_color TEXT, updated_at INTEGER)", "CREATE TABLE IF NOT EXISTS shifts (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, opened_at INTEGER NOT NULL, closed_at INTEGER, opening_amount REAL NOT NULL, closing_amount REAL, status TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id))", "CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, icon TEXT, created_at INTEGER NOT NULL)", "CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER, name TEXT NOT NULL, description TEXT, price REAL NOT NULL, image TEXT, status TEXT DEFAULT 'available', created_at INTEGER NOT NULL, FOREIGN KEY(category_id) REFERENCES categories(id))", "CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, shift_id INTEGER NOT NULL, customer_name TEXT, total REAL NOT NULL, payment_method TEXT, status TEXT NOT NULL, created_at INTEGER NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(shift_id) REFERENCES shifts(id))", "CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, price REAL NOT NULL, subtotal REAL NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id), FOREIGN KEY(product_id) REFERENCES products(id))", "CREATE TABLE IF NOT EXISTS order_payments (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, payment_method TEXT NOT NULL, amount REAL NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id))"};
   }

   public static String[] getDefaultDataStatements() {
      long now = System.currentTimeMillis();
      return new String[]{"INSERT OR IGNORE INTO company_config (id, company_name, username, pin, primary_color, updated_at) VALUES (1, '', '', '', '#FF6B35', " + now + ")", "INSERT OR IGNORE INTO categories (id, name, icon, created_at) VALUES (1, 'Hamburguesas', '\ud83c\udf54', " + now + ")", "INSERT OR IGNORE INTO categories (id, name, icon, created_at) VALUES (2, 'Pizzas', '\ud83c\udf55', " + now + ")", "INSERT OR IGNORE INTO categories (id, name, icon, created_at) VALUES (3, 'Bebidas', '\ud83e\udd64', " + now + ")", "INSERT OR IGNORE INTO categories (id, name, icon, created_at) VALUES (4, 'Postres', '\ud83c\udf70', " + now + ")", "INSERT OR IGNORE INTO products (id, category_id, name, description, price, status, created_at) VALUES (1, 1, 'Classic Burger', 'Carne res, queso, lechuga', 85.0, 'available', " + now + ")", "INSERT OR IGNORE INTO products (id, category_id, name, description, price, status, created_at) VALUES (2, 1, 'Mega Bacon', 'Doble carne, extra tocino', 120.0, 'available', " + now + ")", "INSERT OR IGNORE INTO products (id, category_id, name, description, price, status, created_at) VALUES (3, 2, 'Pepperoni Classic', 'Mucha mozzarella y pepperoni', 150.0, 'available', " + now + ")", "INSERT OR IGNORE INTO products (id, category_id, name, description, price, status, created_at) VALUES (4, 3, 'Coca Cola 600ml', 'Bien fría', 25.0, 'available', " + now + ")", "INSERT OR IGNORE INTO products (id, category_id, name, description, price, status, created_at) VALUES (5, 4, 'Cheesecake', 'Frutos rojos', 45.0, 'available', " + now + ")"};
   }
}
